server:
   port: 8081
spring:
  application: 
     name: product-service
  cloud: 
     config:
        import-check:  
           enable: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

